AZURE_API_KEY = "ACMAvytOGdUVjjqbAepgJa1QsirxDkHnTbB2p2syPDPls580uF8uJQQJ99BFACfhMk5XJ3w3AAAAACOGOQ4Z"
AZURE_API_ENDPOINT = "https://ai-sieffersprojecthub149512100299.openai.azure.com/openai/deployments/RSMNL-ICS-TP-LocalFile-gpt-4o/chat/completions?api-version=2025-01-01-preview"
EMBEDDING_ENDPOINT = "https://ai-sieffersprojecthub149512100299.openai.azure.com/openai/deployments/text-embedding-ada-002-test/embeddings?api-version=2023-05-15"
